name = "Darkroad"
license = "GPLv2"
licenselink = "//github.com/Shadow53/Darkroad/blob/master/LICENSE.md"
description = "Darkroad is a responsive, clean and content-focused dark theme for Hugo."
homepage = "//github.com/Shadow53/Darkroad/"
tags = ["blog", "responsive", "widgets", "rss", "disqus", "wordpress"]
features = ["blog", "responsive", "widgets", "rss", "disqus", "wordpress"]
min_version = 0.17

[author]
  name = "Shadow53"
  homepage = "//github.com/Shadow53"

# If porting an existing theme
[original]
  name = "Mainroad"
  homepage = "//github.com/vimux/mainroad/"
  repo = "//github.com/vimux/mainroad/"
